// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceConsumption.proto

package com.ProjectSmartOffice;

public interface ConsumptionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServiceConsumption.ConsumptionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The current electricity consumption of the office in watts
   * </pre>
   *
   * <code>string consumption = 1;</code>
   */
  java.lang.String getConsumption();
  /**
   * <pre>
   * The current electricity consumption of the office in watts
   * </pre>
   *
   * <code>string consumption = 1;</code>
   */
  com.google.protobuf.ByteString
      getConsumptionBytes();
}
