// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceConsumption.proto

package com.ProjectSmartOffice;

public interface ConsumptionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServiceConsumption.ConsumptionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * No fields needed
   * </pre>
   *
   * <code>string consumptionValue = 1;</code>
   */
  java.lang.String getConsumptionValue();
  /**
   * <pre>
   * No fields needed
   * </pre>
   *
   * <code>string consumptionValue = 1;</code>
   */
  com.google.protobuf.ByteString
      getConsumptionValueBytes();

  /**
   * <code>string month = 2;</code>
   */
  java.lang.String getMonth();
  /**
   * <code>string month = 2;</code>
   */
  com.google.protobuf.ByteString
      getMonthBytes();
}
