// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceConsumption.proto

package com.ProjectSmartOffice;

public interface MaxConsumptionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServiceConsumption.MaxConsumptionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string month = 1;</code>
   */
  java.lang.String getMonth();
  /**
   * <code>string month = 1;</code>
   */
  com.google.protobuf.ByteString
      getMonthBytes();

  /**
   * <code>string consumptionValue = 2;</code>
   */
  java.lang.String getConsumptionValue();
  /**
   * <code>string consumptionValue = 2;</code>
   */
  com.google.protobuf.ByteString
      getConsumptionValueBytes();
}
