// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceConsumption.proto

package com.ProjectSmartOffice;

public interface MaxConsumptionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServiceConsumption.MaxConsumptionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The maximum electricity consumption of the office in watts
   * </pre>
   *
   * <code>string max_consumption = 1;</code>
   */
  java.lang.String getMaxConsumption();
  /**
   * <pre>
   * The maximum electricity consumption of the office in watts
   * </pre>
   *
   * <code>string max_consumption = 1;</code>
   */
  com.google.protobuf.ByteString
      getMaxConsumptionBytes();
}
