// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceConsumption.proto

package com.ProjectSmartOffice;

/**
 * <pre>
 * Request to get the maximum electricity consumption of the office
 * </pre>
 *
 * Protobuf type {@code ServiceConsumption.MaxConsumptionRequest}
 */
public  final class MaxConsumptionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ServiceConsumption.MaxConsumptionRequest)
    MaxConsumptionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MaxConsumptionRequest.newBuilder() to construct.
  private MaxConsumptionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MaxConsumptionRequest() {
    month_ = "";
    consumptionValue_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MaxConsumptionRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            month_ = s;
            break;
          }
          case 16: {

            consumptionValue_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ProjectSmartOffice.ProjectSmartOffice.internal_static_ServiceConsumption_MaxConsumptionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ProjectSmartOffice.ProjectSmartOffice.internal_static_ServiceConsumption_MaxConsumptionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ProjectSmartOffice.MaxConsumptionRequest.class, com.ProjectSmartOffice.MaxConsumptionRequest.Builder.class);
  }

  public static final int MONTH_FIELD_NUMBER = 1;
  private volatile java.lang.Object month_;
  /**
   * <code>string month = 1;</code>
   */
  public java.lang.String getMonth() {
    java.lang.Object ref = month_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      month_ = s;
      return s;
    }
  }
  /**
   * <code>string month = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMonthBytes() {
    java.lang.Object ref = month_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      month_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONSUMPTIONVALUE_FIELD_NUMBER = 2;
  private int consumptionValue_;
  /**
   * <code>int32 consumptionValue = 2;</code>
   */
  public int getConsumptionValue() {
    return consumptionValue_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMonthBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, month_);
    }
    if (consumptionValue_ != 0) {
      output.writeInt32(2, consumptionValue_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMonthBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, month_);
    }
    if (consumptionValue_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, consumptionValue_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ProjectSmartOffice.MaxConsumptionRequest)) {
      return super.equals(obj);
    }
    com.ProjectSmartOffice.MaxConsumptionRequest other = (com.ProjectSmartOffice.MaxConsumptionRequest) obj;

    boolean result = true;
    result = result && getMonth()
        .equals(other.getMonth());
    result = result && (getConsumptionValue()
        == other.getConsumptionValue());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MONTH_FIELD_NUMBER;
    hash = (53 * hash) + getMonth().hashCode();
    hash = (37 * hash) + CONSUMPTIONVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getConsumptionValue();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ProjectSmartOffice.MaxConsumptionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ProjectSmartOffice.MaxConsumptionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ProjectSmartOffice.MaxConsumptionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ProjectSmartOffice.MaxConsumptionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ProjectSmartOffice.MaxConsumptionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ProjectSmartOffice.MaxConsumptionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ProjectSmartOffice.MaxConsumptionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ProjectSmartOffice.MaxConsumptionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ProjectSmartOffice.MaxConsumptionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ProjectSmartOffice.MaxConsumptionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ProjectSmartOffice.MaxConsumptionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ProjectSmartOffice.MaxConsumptionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ProjectSmartOffice.MaxConsumptionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request to get the maximum electricity consumption of the office
   * </pre>
   *
   * Protobuf type {@code ServiceConsumption.MaxConsumptionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ServiceConsumption.MaxConsumptionRequest)
      com.ProjectSmartOffice.MaxConsumptionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ProjectSmartOffice.ProjectSmartOffice.internal_static_ServiceConsumption_MaxConsumptionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ProjectSmartOffice.ProjectSmartOffice.internal_static_ServiceConsumption_MaxConsumptionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ProjectSmartOffice.MaxConsumptionRequest.class, com.ProjectSmartOffice.MaxConsumptionRequest.Builder.class);
    }

    // Construct using com.ProjectSmartOffice.MaxConsumptionRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      month_ = "";

      consumptionValue_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ProjectSmartOffice.ProjectSmartOffice.internal_static_ServiceConsumption_MaxConsumptionRequest_descriptor;
    }

    @java.lang.Override
    public com.ProjectSmartOffice.MaxConsumptionRequest getDefaultInstanceForType() {
      return com.ProjectSmartOffice.MaxConsumptionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.ProjectSmartOffice.MaxConsumptionRequest build() {
      com.ProjectSmartOffice.MaxConsumptionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ProjectSmartOffice.MaxConsumptionRequest buildPartial() {
      com.ProjectSmartOffice.MaxConsumptionRequest result = new com.ProjectSmartOffice.MaxConsumptionRequest(this);
      result.month_ = month_;
      result.consumptionValue_ = consumptionValue_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ProjectSmartOffice.MaxConsumptionRequest) {
        return mergeFrom((com.ProjectSmartOffice.MaxConsumptionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ProjectSmartOffice.MaxConsumptionRequest other) {
      if (other == com.ProjectSmartOffice.MaxConsumptionRequest.getDefaultInstance()) return this;
      if (!other.getMonth().isEmpty()) {
        month_ = other.month_;
        onChanged();
      }
      if (other.getConsumptionValue() != 0) {
        setConsumptionValue(other.getConsumptionValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ProjectSmartOffice.MaxConsumptionRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ProjectSmartOffice.MaxConsumptionRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object month_ = "";
    /**
     * <code>string month = 1;</code>
     */
    public java.lang.String getMonth() {
      java.lang.Object ref = month_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        month_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string month = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMonthBytes() {
      java.lang.Object ref = month_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        month_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string month = 1;</code>
     */
    public Builder setMonth(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      month_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string month = 1;</code>
     */
    public Builder clearMonth() {
      
      month_ = getDefaultInstance().getMonth();
      onChanged();
      return this;
    }
    /**
     * <code>string month = 1;</code>
     */
    public Builder setMonthBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      month_ = value;
      onChanged();
      return this;
    }

    private int consumptionValue_ ;
    /**
     * <code>int32 consumptionValue = 2;</code>
     */
    public int getConsumptionValue() {
      return consumptionValue_;
    }
    /**
     * <code>int32 consumptionValue = 2;</code>
     */
    public Builder setConsumptionValue(int value) {
      
      consumptionValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 consumptionValue = 2;</code>
     */
    public Builder clearConsumptionValue() {
      
      consumptionValue_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ServiceConsumption.MaxConsumptionRequest)
  }

  // @@protoc_insertion_point(class_scope:ServiceConsumption.MaxConsumptionRequest)
  private static final com.ProjectSmartOffice.MaxConsumptionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ProjectSmartOffice.MaxConsumptionRequest();
  }

  public static com.ProjectSmartOffice.MaxConsumptionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MaxConsumptionRequest>
      PARSER = new com.google.protobuf.AbstractParser<MaxConsumptionRequest>() {
    @java.lang.Override
    public MaxConsumptionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MaxConsumptionRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MaxConsumptionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MaxConsumptionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ProjectSmartOffice.MaxConsumptionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

