// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceConsumption.proto

package com.ProjectSmartOffice;

public interface MinConsumptionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServiceConsumption.MinConsumptionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The minimum electricity consumption of the office in watts
   * </pre>
   *
   * <code>string min_consumption = 1;</code>
   */
  java.lang.String getMinConsumption();
  /**
   * <pre>
   * The minimum electricity consumption of the office in watts
   * </pre>
   *
   * <code>string min_consumption = 1;</code>
   */
  com.google.protobuf.ByteString
      getMinConsumptionBytes();
}
