// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceConsumption.proto

package com.ProjectSmartOffice;

public interface MinConsumptionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServiceConsumption.MinConsumptionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The minimum electricity consumption of the office in watts
   * </pre>
   *
   * <code>double min_consumption = 1;</code>
   */
  double getMinConsumption();
}
