// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceConsumption.proto

package com.ProjectSmartOffice;

public interface MinConsumptionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServiceConsumption.MinConsumptionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string month = 1;</code>
   */
  java.lang.String getMonth();
  /**
   * <code>string month = 1;</code>
   */
  com.google.protobuf.ByteString
      getMonthBytes();

  /**
   * <code>int32 consumptionValue = 2;</code>
   */
  int getConsumptionValue();
}
