// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceConsumption.proto

package com.ProjectSmartOffice;

public final class ProjectSmartOfficeImpl {
  private ProjectSmartOfficeImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceConsumption_ConsumptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServiceConsumption_ConsumptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceConsumption_ConsumptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServiceConsumption_ConsumptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceConsumption_MaxConsumptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServiceConsumption_MaxConsumptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceConsumption_MaxConsumptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServiceConsumption_MaxConsumptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceConsumption_MinConsumptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServiceConsumption_MinConsumptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceConsumption_MinConsumptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServiceConsumption_MinConsumptionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ServiceConsumption.proto\022\022ServiceConsu" +
      "mption\"=\n\022ConsumptionRequest\022\030\n\020consumpt" +
      "ionValue\030\001 \001(\t\022\r\n\005month\030\002 \001(\t\"*\n\023Consump" +
      "tionResponse\022\023\n\013consumption\030\001 \001(\t\"@\n\025Max" +
      "ConsumptionRequest\022\r\n\005month\030\001 \001(\t\022\030\n\020con" +
      "sumptionValue\030\002 \001(\t\"1\n\026MaxConsumptionRes" +
      "ponse\022\027\n\017max_consumption\030\001 \001(\t\"@\n\025MinCon" +
      "sumptionRequest\022\r\n\005month\030\001 \001(\t\022\030\n\020consum" +
      "ptionValue\030\002 \001(\t\"1\n\026MinConsumptionRespon" +
      "se\022\027\n\017min_consumption\030\001 \001(\t2\347\002\n\035SmartOff" +
      "iceElectricityService\022j\n\025GetCurrentConsu" +
      "mption\022&.ServiceConsumption.ConsumptionR" +
      "equest\032\'.ServiceConsumption.ConsumptionR" +
      "esponse\"\000\022l\n\021GetMaxConsumption\022).Service" +
      "Consumption.MaxConsumptionRequest\032*.Serv" +
      "iceConsumption.MaxConsumptionResponse\"\000\022" +
      "l\n\021GetMinConsumption\022).ServiceConsumptio" +
      "n.MinConsumptionRequest\032*.ServiceConsump" +
      "tion.MinConsumptionResponse\"\000B2\n\026com.Pro" +
      "jectSmartOfficeB\026ProjectSmartOfficeImplP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ServiceConsumption_ConsumptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ServiceConsumption_ConsumptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServiceConsumption_ConsumptionRequest_descriptor,
        new java.lang.String[] { "ConsumptionValue", "Month", });
    internal_static_ServiceConsumption_ConsumptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ServiceConsumption_ConsumptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServiceConsumption_ConsumptionResponse_descriptor,
        new java.lang.String[] { "Consumption", });
    internal_static_ServiceConsumption_MaxConsumptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ServiceConsumption_MaxConsumptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServiceConsumption_MaxConsumptionRequest_descriptor,
        new java.lang.String[] { "Month", "ConsumptionValue", });
    internal_static_ServiceConsumption_MaxConsumptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ServiceConsumption_MaxConsumptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServiceConsumption_MaxConsumptionResponse_descriptor,
        new java.lang.String[] { "MaxConsumption", });
    internal_static_ServiceConsumption_MinConsumptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ServiceConsumption_MinConsumptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServiceConsumption_MinConsumptionRequest_descriptor,
        new java.lang.String[] { "Month", "ConsumptionValue", });
    internal_static_ServiceConsumption_MinConsumptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ServiceConsumption_MinConsumptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServiceConsumption_MinConsumptionResponse_descriptor,
        new java.lang.String[] { "MinConsumption", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
