// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceLight.proto

package com.ProjectSmartOffice3;

public final class ProjectSmartOfficeImpl {
  private ProjectSmartOfficeImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceLight_SetLightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServiceLight_SetLightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceLight_SetLightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServiceLight_SetLightResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceLight_SetTemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServiceLight_SetTemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceLight_SetTemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServiceLight_SetTemperatureResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceLight_RoomLightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServiceLight_RoomLightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceLight_RoomLightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServiceLight_RoomLightResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ServiceLight.proto\022\014ServiceLight\"\"\n\017Se" +
      "tLightRequest\022\017\n\007room_id\030\001 \001(\t\"!\n\020SetLig" +
      "htResponse\022\r\n\005light\030\001 \001(\t\":\n\025SetTemperat" +
      "ureRequest\022\014\n\004room\030\001 \001(\t\022\023\n\013temperature\030" +
      "\002 \001(\t\";\n\026SetTemperatureResponse\022\014\n\004room\030" +
      "\001 \001(\t\022\023\n\013temperature\030\002 \001(\t\"6\n\020RoomLightR" +
      "equest\022\r\n\005rooms\030\001 \001(\t\022\023\n\013light_state\030\002 \001" +
      "(\t\"7\n\021RoomLightResponse\022\r\n\005rooms\030\001 \001(\t\022\023" +
      "\n\013light_state\030\002 \001(\t2\250\002\n\027SmartOfficeLight" +
      "Service\022O\n\014SetRoomLight\022\035.ServiceLight.S" +
      "etLightRequest\032\036.ServiceLight.SetLightRe" +
      "sponse\"\000\022a\n\022SetRoomTemperature\022#.Service" +
      "Light.SetTemperatureRequest\032$.ServiceLig" +
      "ht.SetTemperatureResponse\"\000\022Y\n\020ControlRo" +
      "omLight\022\036.ServiceLight.RoomLightRequest\032" +
      "\037.ServiceLight.RoomLightResponse\"\000(\0010\001B3" +
      "\n\027com.ProjectSmartOffice3B\026ProjectSmartO" +
      "fficeImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ServiceLight_SetLightRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ServiceLight_SetLightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServiceLight_SetLightRequest_descriptor,
        new java.lang.String[] { "RoomId", });
    internal_static_ServiceLight_SetLightResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ServiceLight_SetLightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServiceLight_SetLightResponse_descriptor,
        new java.lang.String[] { "Light", });
    internal_static_ServiceLight_SetTemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ServiceLight_SetTemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServiceLight_SetTemperatureRequest_descriptor,
        new java.lang.String[] { "Room", "Temperature", });
    internal_static_ServiceLight_SetTemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ServiceLight_SetTemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServiceLight_SetTemperatureResponse_descriptor,
        new java.lang.String[] { "Room", "Temperature", });
    internal_static_ServiceLight_RoomLightRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ServiceLight_RoomLightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServiceLight_RoomLightRequest_descriptor,
        new java.lang.String[] { "Rooms", "LightState", });
    internal_static_ServiceLight_RoomLightResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ServiceLight_RoomLightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServiceLight_RoomLightResponse_descriptor,
        new java.lang.String[] { "Rooms", "LightState", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
