// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceLight.proto

package com.ProjectSmartOffice3;

public interface RoomLightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServiceLight.RoomLightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string rooms = 1;</code>
   */
  java.lang.String getRooms();
  /**
   * <code>string rooms = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomsBytes();

  /**
   * <code>string light_state = 2;</code>
   */
  java.lang.String getLightState();
  /**
   * <code>string light_state = 2;</code>
   */
  com.google.protobuf.ByteString
      getLightStateBytes();
}
