// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceLight.proto

package com.ProjectSmartOffice3;

public interface SetLightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServiceLight.SetLightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string light = 1;</code>
   */
  java.lang.String getLight();
  /**
   * <code>string light = 1;</code>
   */
  com.google.protobuf.ByteString
      getLightBytes();
}
