// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceLight.proto

package com.ProjectSmartOffice3;

public interface SetTemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServiceLight.SetTemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string room = 1;</code>
   */
  java.lang.String getRoom();
  /**
   * <code>string room = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomBytes();

  /**
   * <code>string temperature = 2;</code>
   */
  java.lang.String getTemperature();
  /**
   * <code>string temperature = 2;</code>
   */
  com.google.protobuf.ByteString
      getTemperatureBytes();
}
