// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceTemperature.proto

package com.ProjectSmartOffice2;

public interface TemperatureRangeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServiceTemperature.TemperatureRangeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * True if the temperature readings are within the specified range, false otherwise
   * </pre>
   *
   * <code>bool range = 1;</code>
   */
  boolean getRange();
}
