// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceTemperature.proto

package com.ProjectSmartOffice2;

public interface TemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServiceTemperature.TemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string morningtemperature = 1;</code>
   */
  java.lang.String getMorningtemperature();
  /**
   * <code>string morningtemperature = 1;</code>
   */
  com.google.protobuf.ByteString
      getMorningtemperatureBytes();

  /**
   * <code>string afternoontemperature = 2;</code>
   */
  java.lang.String getAfternoontemperature();
  /**
   * <code>string afternoontemperature = 2;</code>
   */
  com.google.protobuf.ByteString
      getAfternoontemperatureBytes();
}
