// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceTemperature.proto

package com.ProjectSmartOffice2;

/**
 * <pre>
 *Request containing a series of temperature readings to calculate the average temperature
 * </pre>
 *
 * Protobuf type {@code ServiceTemperature.TemperatureAverageRequest}
 */
public  final class TemperatureAverageRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ServiceTemperature.TemperatureAverageRequest)
    TemperatureAverageRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TemperatureAverageRequest.newBuilder() to construct.
  private TemperatureAverageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TemperatureAverageRequest() {
    temperatures_ = 0D;
    temperatures2_ = 0D;
    temperatures3_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TemperatureAverageRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            temperatures_ = input.readDouble();
            break;
          }
          case 17: {

            temperatures2_ = input.readDouble();
            break;
          }
          case 25: {

            temperatures3_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ProjectSmartOffice2.ProjectSmartOfficeImpl.internal_static_ServiceTemperature_TemperatureAverageRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ProjectSmartOffice2.ProjectSmartOfficeImpl.internal_static_ServiceTemperature_TemperatureAverageRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ProjectSmartOffice2.TemperatureAverageRequest.class, com.ProjectSmartOffice2.TemperatureAverageRequest.Builder.class);
  }

  public static final int TEMPERATURES_FIELD_NUMBER = 1;
  private double temperatures_;
  /**
   * <code>double temperatures = 1;</code>
   */
  public double getTemperatures() {
    return temperatures_;
  }

  public static final int TEMPERATURES2_FIELD_NUMBER = 2;
  private double temperatures2_;
  /**
   * <code>double temperatures2 = 2;</code>
   */
  public double getTemperatures2() {
    return temperatures2_;
  }

  public static final int TEMPERATURES3_FIELD_NUMBER = 3;
  private double temperatures3_;
  /**
   * <code>double temperatures3 = 3;</code>
   */
  public double getTemperatures3() {
    return temperatures3_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (temperatures_ != 0D) {
      output.writeDouble(1, temperatures_);
    }
    if (temperatures2_ != 0D) {
      output.writeDouble(2, temperatures2_);
    }
    if (temperatures3_ != 0D) {
      output.writeDouble(3, temperatures3_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (temperatures_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, temperatures_);
    }
    if (temperatures2_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, temperatures2_);
    }
    if (temperatures3_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, temperatures3_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ProjectSmartOffice2.TemperatureAverageRequest)) {
      return super.equals(obj);
    }
    com.ProjectSmartOffice2.TemperatureAverageRequest other = (com.ProjectSmartOffice2.TemperatureAverageRequest) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getTemperatures())
        == java.lang.Double.doubleToLongBits(
            other.getTemperatures()));
    result = result && (
        java.lang.Double.doubleToLongBits(getTemperatures2())
        == java.lang.Double.doubleToLongBits(
            other.getTemperatures2()));
    result = result && (
        java.lang.Double.doubleToLongBits(getTemperatures3())
        == java.lang.Double.doubleToLongBits(
            other.getTemperatures3()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEMPERATURES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTemperatures()));
    hash = (37 * hash) + TEMPERATURES2_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTemperatures2()));
    hash = (37 * hash) + TEMPERATURES3_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTemperatures3()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ProjectSmartOffice2.TemperatureAverageRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ProjectSmartOffice2.TemperatureAverageRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ProjectSmartOffice2.TemperatureAverageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ProjectSmartOffice2.TemperatureAverageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ProjectSmartOffice2.TemperatureAverageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ProjectSmartOffice2.TemperatureAverageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ProjectSmartOffice2.TemperatureAverageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ProjectSmartOffice2.TemperatureAverageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ProjectSmartOffice2.TemperatureAverageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ProjectSmartOffice2.TemperatureAverageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ProjectSmartOffice2.TemperatureAverageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ProjectSmartOffice2.TemperatureAverageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ProjectSmartOffice2.TemperatureAverageRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *Request containing a series of temperature readings to calculate the average temperature
   * </pre>
   *
   * Protobuf type {@code ServiceTemperature.TemperatureAverageRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ServiceTemperature.TemperatureAverageRequest)
      com.ProjectSmartOffice2.TemperatureAverageRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ProjectSmartOffice2.ProjectSmartOfficeImpl.internal_static_ServiceTemperature_TemperatureAverageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ProjectSmartOffice2.ProjectSmartOfficeImpl.internal_static_ServiceTemperature_TemperatureAverageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ProjectSmartOffice2.TemperatureAverageRequest.class, com.ProjectSmartOffice2.TemperatureAverageRequest.Builder.class);
    }

    // Construct using com.ProjectSmartOffice2.TemperatureAverageRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      temperatures_ = 0D;

      temperatures2_ = 0D;

      temperatures3_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ProjectSmartOffice2.ProjectSmartOfficeImpl.internal_static_ServiceTemperature_TemperatureAverageRequest_descriptor;
    }

    @java.lang.Override
    public com.ProjectSmartOffice2.TemperatureAverageRequest getDefaultInstanceForType() {
      return com.ProjectSmartOffice2.TemperatureAverageRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.ProjectSmartOffice2.TemperatureAverageRequest build() {
      com.ProjectSmartOffice2.TemperatureAverageRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ProjectSmartOffice2.TemperatureAverageRequest buildPartial() {
      com.ProjectSmartOffice2.TemperatureAverageRequest result = new com.ProjectSmartOffice2.TemperatureAverageRequest(this);
      result.temperatures_ = temperatures_;
      result.temperatures2_ = temperatures2_;
      result.temperatures3_ = temperatures3_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ProjectSmartOffice2.TemperatureAverageRequest) {
        return mergeFrom((com.ProjectSmartOffice2.TemperatureAverageRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ProjectSmartOffice2.TemperatureAverageRequest other) {
      if (other == com.ProjectSmartOffice2.TemperatureAverageRequest.getDefaultInstance()) return this;
      if (other.getTemperatures() != 0D) {
        setTemperatures(other.getTemperatures());
      }
      if (other.getTemperatures2() != 0D) {
        setTemperatures2(other.getTemperatures2());
      }
      if (other.getTemperatures3() != 0D) {
        setTemperatures3(other.getTemperatures3());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ProjectSmartOffice2.TemperatureAverageRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ProjectSmartOffice2.TemperatureAverageRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double temperatures_ ;
    /**
     * <code>double temperatures = 1;</code>
     */
    public double getTemperatures() {
      return temperatures_;
    }
    /**
     * <code>double temperatures = 1;</code>
     */
    public Builder setTemperatures(double value) {
      
      temperatures_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double temperatures = 1;</code>
     */
    public Builder clearTemperatures() {
      
      temperatures_ = 0D;
      onChanged();
      return this;
    }

    private double temperatures2_ ;
    /**
     * <code>double temperatures2 = 2;</code>
     */
    public double getTemperatures2() {
      return temperatures2_;
    }
    /**
     * <code>double temperatures2 = 2;</code>
     */
    public Builder setTemperatures2(double value) {
      
      temperatures2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double temperatures2 = 2;</code>
     */
    public Builder clearTemperatures2() {
      
      temperatures2_ = 0D;
      onChanged();
      return this;
    }

    private double temperatures3_ ;
    /**
     * <code>double temperatures3 = 3;</code>
     */
    public double getTemperatures3() {
      return temperatures3_;
    }
    /**
     * <code>double temperatures3 = 3;</code>
     */
    public Builder setTemperatures3(double value) {
      
      temperatures3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double temperatures3 = 3;</code>
     */
    public Builder clearTemperatures3() {
      
      temperatures3_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ServiceTemperature.TemperatureAverageRequest)
  }

  // @@protoc_insertion_point(class_scope:ServiceTemperature.TemperatureAverageRequest)
  private static final com.ProjectSmartOffice2.TemperatureAverageRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ProjectSmartOffice2.TemperatureAverageRequest();
  }

  public static com.ProjectSmartOffice2.TemperatureAverageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TemperatureAverageRequest>
      PARSER = new com.google.protobuf.AbstractParser<TemperatureAverageRequest>() {
    @java.lang.Override
    public TemperatureAverageRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TemperatureAverageRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TemperatureAverageRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TemperatureAverageRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ProjectSmartOffice2.TemperatureAverageRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

