// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceTemperature.proto

package com.ProjectSmartOffice2;

/**
 * <pre>
 * Request containing a series of temperature readings to determine if the temperature is within a specified range
 * </pre>
 *
 * Protobuf type {@code ServiceTemperature.TemperatureRangeRequest}
 */
public  final class TemperatureRangeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ServiceTemperature.TemperatureRangeRequest)
    TemperatureRangeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TemperatureRangeRequest.newBuilder() to construct.
  private TemperatureRangeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TemperatureRangeRequest() {
    rangetemperatures_ = 0D;
    lowerRange_ = 0D;
    upperRange_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TemperatureRangeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            rangetemperatures_ = input.readDouble();
            break;
          }
          case 17: {

            lowerRange_ = input.readDouble();
            break;
          }
          case 25: {

            upperRange_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ProjectSmartOffice2.ProjectSmartOfficeImpl.internal_static_ServiceTemperature_TemperatureRangeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ProjectSmartOffice2.ProjectSmartOfficeImpl.internal_static_ServiceTemperature_TemperatureRangeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ProjectSmartOffice2.TemperatureRangeRequest.class, com.ProjectSmartOffice2.TemperatureRangeRequest.Builder.class);
  }

  public static final int RANGETEMPERATURES_FIELD_NUMBER = 1;
  private double rangetemperatures_;
  /**
   * <pre>
   * A stream of temperature readings in degrees Celsius
   * </pre>
   *
   * <code>double rangetemperatures = 1;</code>
   */
  public double getRangetemperatures() {
    return rangetemperatures_;
  }

  public static final int LOWER_RANGE_FIELD_NUMBER = 2;
  private double lowerRange_;
  /**
   * <pre>
   * The lower bound of the temperature range in degrees Celsius
   * </pre>
   *
   * <code>double lower_range = 2;</code>
   */
  public double getLowerRange() {
    return lowerRange_;
  }

  public static final int UPPER_RANGE_FIELD_NUMBER = 3;
  private double upperRange_;
  /**
   * <pre>
   * The upper bound of the temperature range in degrees Celsius
   * </pre>
   *
   * <code>double upper_range = 3;</code>
   */
  public double getUpperRange() {
    return upperRange_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (rangetemperatures_ != 0D) {
      output.writeDouble(1, rangetemperatures_);
    }
    if (lowerRange_ != 0D) {
      output.writeDouble(2, lowerRange_);
    }
    if (upperRange_ != 0D) {
      output.writeDouble(3, upperRange_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (rangetemperatures_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, rangetemperatures_);
    }
    if (lowerRange_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, lowerRange_);
    }
    if (upperRange_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, upperRange_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ProjectSmartOffice2.TemperatureRangeRequest)) {
      return super.equals(obj);
    }
    com.ProjectSmartOffice2.TemperatureRangeRequest other = (com.ProjectSmartOffice2.TemperatureRangeRequest) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getRangetemperatures())
        == java.lang.Double.doubleToLongBits(
            other.getRangetemperatures()));
    result = result && (
        java.lang.Double.doubleToLongBits(getLowerRange())
        == java.lang.Double.doubleToLongBits(
            other.getLowerRange()));
    result = result && (
        java.lang.Double.doubleToLongBits(getUpperRange())
        == java.lang.Double.doubleToLongBits(
            other.getUpperRange()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RANGETEMPERATURES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRangetemperatures()));
    hash = (37 * hash) + LOWER_RANGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLowerRange()));
    hash = (37 * hash) + UPPER_RANGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getUpperRange()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ProjectSmartOffice2.TemperatureRangeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ProjectSmartOffice2.TemperatureRangeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ProjectSmartOffice2.TemperatureRangeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ProjectSmartOffice2.TemperatureRangeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ProjectSmartOffice2.TemperatureRangeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ProjectSmartOffice2.TemperatureRangeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ProjectSmartOffice2.TemperatureRangeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ProjectSmartOffice2.TemperatureRangeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ProjectSmartOffice2.TemperatureRangeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ProjectSmartOffice2.TemperatureRangeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ProjectSmartOffice2.TemperatureRangeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ProjectSmartOffice2.TemperatureRangeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ProjectSmartOffice2.TemperatureRangeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request containing a series of temperature readings to determine if the temperature is within a specified range
   * </pre>
   *
   * Protobuf type {@code ServiceTemperature.TemperatureRangeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ServiceTemperature.TemperatureRangeRequest)
      com.ProjectSmartOffice2.TemperatureRangeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ProjectSmartOffice2.ProjectSmartOfficeImpl.internal_static_ServiceTemperature_TemperatureRangeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ProjectSmartOffice2.ProjectSmartOfficeImpl.internal_static_ServiceTemperature_TemperatureRangeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ProjectSmartOffice2.TemperatureRangeRequest.class, com.ProjectSmartOffice2.TemperatureRangeRequest.Builder.class);
    }

    // Construct using com.ProjectSmartOffice2.TemperatureRangeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      rangetemperatures_ = 0D;

      lowerRange_ = 0D;

      upperRange_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ProjectSmartOffice2.ProjectSmartOfficeImpl.internal_static_ServiceTemperature_TemperatureRangeRequest_descriptor;
    }

    @java.lang.Override
    public com.ProjectSmartOffice2.TemperatureRangeRequest getDefaultInstanceForType() {
      return com.ProjectSmartOffice2.TemperatureRangeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.ProjectSmartOffice2.TemperatureRangeRequest build() {
      com.ProjectSmartOffice2.TemperatureRangeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ProjectSmartOffice2.TemperatureRangeRequest buildPartial() {
      com.ProjectSmartOffice2.TemperatureRangeRequest result = new com.ProjectSmartOffice2.TemperatureRangeRequest(this);
      result.rangetemperatures_ = rangetemperatures_;
      result.lowerRange_ = lowerRange_;
      result.upperRange_ = upperRange_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ProjectSmartOffice2.TemperatureRangeRequest) {
        return mergeFrom((com.ProjectSmartOffice2.TemperatureRangeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ProjectSmartOffice2.TemperatureRangeRequest other) {
      if (other == com.ProjectSmartOffice2.TemperatureRangeRequest.getDefaultInstance()) return this;
      if (other.getRangetemperatures() != 0D) {
        setRangetemperatures(other.getRangetemperatures());
      }
      if (other.getLowerRange() != 0D) {
        setLowerRange(other.getLowerRange());
      }
      if (other.getUpperRange() != 0D) {
        setUpperRange(other.getUpperRange());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ProjectSmartOffice2.TemperatureRangeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ProjectSmartOffice2.TemperatureRangeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double rangetemperatures_ ;
    /**
     * <pre>
     * A stream of temperature readings in degrees Celsius
     * </pre>
     *
     * <code>double rangetemperatures = 1;</code>
     */
    public double getRangetemperatures() {
      return rangetemperatures_;
    }
    /**
     * <pre>
     * A stream of temperature readings in degrees Celsius
     * </pre>
     *
     * <code>double rangetemperatures = 1;</code>
     */
    public Builder setRangetemperatures(double value) {
      
      rangetemperatures_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A stream of temperature readings in degrees Celsius
     * </pre>
     *
     * <code>double rangetemperatures = 1;</code>
     */
    public Builder clearRangetemperatures() {
      
      rangetemperatures_ = 0D;
      onChanged();
      return this;
    }

    private double lowerRange_ ;
    /**
     * <pre>
     * The lower bound of the temperature range in degrees Celsius
     * </pre>
     *
     * <code>double lower_range = 2;</code>
     */
    public double getLowerRange() {
      return lowerRange_;
    }
    /**
     * <pre>
     * The lower bound of the temperature range in degrees Celsius
     * </pre>
     *
     * <code>double lower_range = 2;</code>
     */
    public Builder setLowerRange(double value) {
      
      lowerRange_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The lower bound of the temperature range in degrees Celsius
     * </pre>
     *
     * <code>double lower_range = 2;</code>
     */
    public Builder clearLowerRange() {
      
      lowerRange_ = 0D;
      onChanged();
      return this;
    }

    private double upperRange_ ;
    /**
     * <pre>
     * The upper bound of the temperature range in degrees Celsius
     * </pre>
     *
     * <code>double upper_range = 3;</code>
     */
    public double getUpperRange() {
      return upperRange_;
    }
    /**
     * <pre>
     * The upper bound of the temperature range in degrees Celsius
     * </pre>
     *
     * <code>double upper_range = 3;</code>
     */
    public Builder setUpperRange(double value) {
      
      upperRange_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The upper bound of the temperature range in degrees Celsius
     * </pre>
     *
     * <code>double upper_range = 3;</code>
     */
    public Builder clearUpperRange() {
      
      upperRange_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ServiceTemperature.TemperatureRangeRequest)
  }

  // @@protoc_insertion_point(class_scope:ServiceTemperature.TemperatureRangeRequest)
  private static final com.ProjectSmartOffice2.TemperatureRangeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ProjectSmartOffice2.TemperatureRangeRequest();
  }

  public static com.ProjectSmartOffice2.TemperatureRangeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TemperatureRangeRequest>
      PARSER = new com.google.protobuf.AbstractParser<TemperatureRangeRequest>() {
    @java.lang.Override
    public TemperatureRangeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TemperatureRangeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TemperatureRangeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TemperatureRangeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ProjectSmartOffice2.TemperatureRangeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

