// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceTemperature.proto

package com.ProjectSmartOffice2;

public interface TemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServiceTemperature.TemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string temperature = 20;</code>
   */
  java.lang.String getTemperature();
  /**
   * <code>string temperature = 20;</code>
   */
  com.google.protobuf.ByteString
      getTemperatureBytes();
}
