// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceTemperature.proto

package com.ProjectSmartOffice2;

public interface TemperatureAverageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServiceTemperature.TemperatureAverageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double average_temperature = 2;</code>
   */
  double getAverageTemperature();
}
