// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceTemperature.proto

package com.ProjectSmartOffice2;

public interface TemperatureRangeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServiceTemperature.TemperatureRangeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A stream of temperature readings in degrees Celsius
   * </pre>
   *
   * <code>double rangetemperatures = 1;</code>
   */
  double getRangetemperatures();

  /**
   * <pre>
   * The lower bound of the temperature range in degrees Celsius
   * </pre>
   *
   * <code>double lower_range = 2;</code>
   */
  double getLowerRange();

  /**
   * <pre>
   * The upper bound of the temperature range in degrees Celsius
   * </pre>
   *
   * <code>double upper_range = 3;</code>
   */
  double getUpperRange();
}
