// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceTemperature.proto

package com.ProjectSmartOffice2;

public interface TemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServiceTemperature.TemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string trequest = 1;</code>
   */
  java.lang.String getTrequest();
  /**
   * <code>string trequest = 1;</code>
   */
  com.google.protobuf.ByteString
      getTrequestBytes();
}
