// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceTemperature.proto

package com.ProjectSmartOffice2;

public interface TemperatureAverageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServiceTemperature.TemperatureAverageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double temperatures = 1;</code>
   */
  double getTemperatures();

  /**
   * <code>double temperatures2 = 2;</code>
   */
  double getTemperatures2();

  /**
   * <code>double temperatures3 = 3;</code>
   */
  double getTemperatures3();
}
